version: "3"
services:
  run_pyinstaller:
    image: linaro/wine-arm64
    volumes:
      - ./clangarm64:/clangarm64
      - ../:/src
    command: wine-arm64 cmd /c "cd /src/packaging && set PATH=/clangarm64/bin;%PATH% && pyinstaller libresvip-gui.spec"
